### ISSUE TITLE
Summer 2018 todo list

### ISSUE THREAD

**Issue by noahbass** [ACMatUC/acmatuc.github.io#44]
- [x] Update office hours section to say they'll return in the Fall
- [x] Update exec photos and exec content (including chair committee members)
- [x] Add slack badge to website with current number users / total users (similar to the [slackin badge](https://github.com/gliderlabs/slack/blob/master/slackin/README.md#svg))
- [ ] [Enable https for our custom domain](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) on GitHub Pages, remove the Cloudflare https
- [ ] New events page
  - [ ] Add more information for each meeting (more than just a calendar)
- [ ] Support blog posts
  - [ ] Support a few different categories like general ACM updates, meeting recaps, and member posts
  - [ ] Why we're adding this feature: for publishing general ACM updates, to feature members and their work, and to recap general body meetings (an embedded youtube video with optional comments from the speaker)
- [x] Add link to the constitution on GitHub
- [x] Add link to our LinkedIn page
- More stuff as we think of it
