### ISSUE TITLE
Fall 2018 TODO

### ISSUE THREAD

**Issue by noahbass** [ACMatUC/acmatuc.github.io#47]
- [x] Sidebar
  - [x] Link out to makeuc.io
  - [x] Link out to revolutionuc.com
  - [x] Link out to acm-w at uc
